# Generated by Django 4.0.1 on 2022-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairytales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairytale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
