# Generated by Django 4.0.1 on 2022-02-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairytales', '0002_fairytale_vector_column_and_more'),
    ]

    operations = [
        # migrations.RunSQL(
        #     sql='''
        #       ALTER TABLE fairytale ADD COLUMN vector_column tsvector GENERATED ALWAYS AS (
        #         setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        #         setweight(to_tsvector('english', coalesce(body,'')), 'B') ||
        #         setweight(to_tsvector('english', coalesce(author,'')), 'C')
        #       ) STORED;
        #     ''',

        #     reverse_sql = '''
        #       ALTER TABLE fairytale DROP COLUMN vector_column;
        #     '''
        # ),

        migrations.RunSQL(
            sql='''
            CREATE TRIGGER fairytale_update_trigger
            BEFORE INSERT OR UPDATE OF title, body, author, vector_column
            ON fairytales_fairytale
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              vector_column, 'pg_catalog.english', title, body, author);

            UPDATE fairytales_fairytale SET vector_column = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS fairytale_update_trigger
            ON fairytales_fairytale;
            '''),


    ]
