# Generated by Django 4.0.1 on 2022-02-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairytales", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
