# Generated by Django 4.0.1 on 2022-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairytales", "0007_alter_profile_image_alter_profile_prefered_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="fairytale",
            name="category",
            field=models.CharField(default="uncategorized", max_length=100),
        ),
    ]
