# Generated by Django 4.0.1 on 2022-02-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairytales', '0008_category_fairytale_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
