# Generated by Django 4.0.1 on 2022-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairytales', '0010_alter_profile_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairytale',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
